wget http://zibase.net/zodianet/zodiaWeb/icon1/120pix/$1 -O ./1c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon2/120pix/$1 -O ./2c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon3/120pix/$1 -O ./3c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon4/120pix/$1 -O ./4c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon5/120pix/$1 -O ./5c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon6/120pix/$1 -O ./6c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon7/120pix/$1 -O ./7c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon8/120pix/$1 -O ./8c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon9/120pix/$1 -O ./9c_$1
wget http://zibase.net/zodianet/zodiaWeb/icon1/120pix_gray/$1 -O ./1g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon2/120pix_gray/$1 -O ./2g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon3/120pix_gray/$1 -O ./3g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon4/120pix_gray/$1 -O ./4g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon5/120pix_gray/$1 -O ./5g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon6/120pix_gray/$1 -O ./6g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon7/120pix_gray/$1 -O ./7g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon8/120pix_gray/$1 -O ./8g_$1
wget http://zibase.net/zodianet/zodiaWeb/icon9/120pix_gray/$1 -O ./9g_$1
